version: '3'

services:
  mysql:
    container_name: mysql_kotlin_jwt
    image: mysql/mysql-server:5.7
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_USER: 'jwt'
      MYSQL_PASSWORD: 1234
      MYSQL_DATABASE: 'kotlin_jwt'
    ports:
      - "3308:3306"
    command:
      - "mysqld"
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"